// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFO_feov9V78DcDGvE7UVS95uNvCiNBmI',
    appId: '1:720369665191:web:687d2cf035c08ca4250782',
    messagingSenderId: '720369665191',
    projectId: 'reddit-app-608b1',
    authDomain: 'reddit-app-608b1.firebaseapp.com',
    storageBucket: 'reddit-app-608b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdNoDIcLZdwZUVvfnz6qN8A4TQbCiMHI',
    appId: '1:720369665191:android:6df84c889b6a7ba9250782',
    messagingSenderId: '720369665191',
    projectId: 'reddit-app-608b1',
    storageBucket: 'reddit-app-608b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATZbHV0Q-aP68Mzij05Civ4OF7NvXAs-I',
    appId: '1:720369665191:ios:43b6bd363645018e250782',
    messagingSenderId: '720369665191',
    projectId: 'reddit-app-608b1',
    storageBucket: 'reddit-app-608b1.appspot.com',
    iosClientId: '720369665191-k2llifrlugad1jb9kvbe11ijeb2ijpgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATZbHV0Q-aP68Mzij05Civ4OF7NvXAs-I',
    appId: '1:720369665191:ios:43b6bd363645018e250782',
    messagingSenderId: '720369665191',
    projectId: 'reddit-app-608b1',
    storageBucket: 'reddit-app-608b1.appspot.com',
    iosClientId: '720369665191-k2llifrlugad1jb9kvbe11ijeb2ijpgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );
}
